# Generated by Django 2.2.5 on 2019-09-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('ip', models.GenericIPAddressField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
